import "./scss/main.scss"

import "./js/geolocation"
import "./js/townSearcher"
import "./js/loadingScreen"
import "./js/errorHandling"
import "./js/geolocation"
import "./js/currentDate"
import "./js/readingInput"
import "./js/localStorage"
import "./js/drawerAnimation"
